### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by sandyfan** [ProjectMatrixx/android#1]
When I open SMS settings, it automatically crashes. I need to turn on the 5G switch, my device is off by default

https://github.com/ProjectMatrixx/android/assets/128270679/ee910b83-b0a6-4516-ac44-68375ac7dc97

**Comment by sandyfan** [comment]
https://paste.crdroid.net/MBNfLK
Crash url

**Comment by bphd** [comment]
@mukesh22584 wer commit
