### ISSUE TITLE
Feature Requests:

### ISSUE THREAD

**Issue by socksprox** [ProjectMatrixx/android#2]
Option to view logs from within settings 
![IMG_2166](https://github.com/ProjectMatrixx/android/assets/36358673/7673c266-e6f6-43a7-9e41-4ef632636aac)
![IMG_2167](https://github.com/ProjectMatrixx/android/assets/36358673/8a74069e-e5fc-4dae-8d34-14d74f39ce70)

Option to select if app should have network permission on install
![IMG_2165](https://github.com/ProjectMatrixx/android/assets/36358673/8006a466-f88a-4477-86d2-fd5585747ebc)

Smart Pixels (shut off pixels to reduce power consumption)
![IMG_2168](https://github.com/ProjectMatrixx/android/assets/36358673/dd9c882d-5cb2-4de0-8f3f-c2d492927972)

**Comment by socksprox** [comment]
Why did you close this @mukesh22584 ? Will it be added, not added?

**Comment by mukesh22584** [comment]
Share issues here:
https://t.me/matrixx_community

**Comment by bphd** [comment]
@mukesh22584 wer commit
