### ISSUE TITLE
ThemeOverlayController: fetched

### ISSUE THREAD

**Issue by Dr-chen99** [ProjectMatrixx/android#3]
failed to parse idmap header of '/data/resource-cache/data@resource-cache@com.android.systemui-accent-aU8D.frro@idmap'

ThemeOverlayController: Applying overlays: android.theme.customization.system_palette -> com.android.systemui:neutral, android.theme.customization.dynamic_color -> com.android.systemui:dynamic, android.theme.customization.accent_color -> com.android.systemui:accent
06-05 17:33:09.580  9402  9402 I ThemeOverlayController: Failed to parse THEME_CUSTOMIZATION_OVERLAY_PACKAGES.

**Comment by bphd** [comment]
@mukesh22584 wer commit
